name: "Harwinder Sidhu"
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year/:month/:day/:title
exclude: [README.md, LICENSE, Makefile]

# Information for the Atom feed
gereksiz:
   author: "Harwinder Sidhu"
   email: "harwinder@gmail.com"
